#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  1 12:12:57 2018

@author: EdenDAbreo
"""

import arcade

class shape(arcade.Sprite):
    
    def _init_ (self)
        
        self.change_x
        
        if self.left < 0:
            self.left = 0
        elif self.right > SCREEN_WIDTH - 1:
            self.right = SCREEN_WIDTH - 1
            
class bullet(arcade.Sprite):
    
    def _init_ (self):
        
        self.change_y
        
        if self.top > SCREEN_HEIGHT - 1:
            self.top = SCREEN_HEIGHT - 1
            
class player(arcade.Sprite):
    
    def _init_(self):
        
        self.change_x
        
        if self.left <0:
            self.left = 0
        elif self.right > SCREEN_WIDTH - 1:
            self.right = SCREEN_WIDTH - 1
        
    
        